#!/bin/bash
# Author: IAN CASSAR

RESET_HASH=$1
COMMIT_COMMENT=$(git show -s --format=%s)
BRANCH_NAME=$(git rev-parse --abbrev-ref HEAD) 

git push origin :$BRANCH_NAME
echo "DELETE"

git reset --soft $1
echo "RESET"

git commit -m $COMMIT_COMMENT
echo "COMMIT LOCAL"

git push -u origin $BRANCH_NAME
echo "PUSH"
